include:
    project: 'cicd/CICDTemplate'
    file: '/.gitlab-ci.api.loopback4.yml'

variables:
  BUILD_IMAGE_NAME: 'image_name'
  SERVICE_NAME: 'zap-scan-service-name'
  EXPOSE_PORT: 3000



unit_test:
  extends: auto_testing
  only:
    - master
  tags:
    - wks-runner01


build_dist:
  extends: npm_build
  only:
    - master
  tags:
    - wks-runner01

build_test:
  extends: build_testimage
  only:
    - master
  tags:
    - wks-runner01

deploy_test:
  extends: deploy_for_test
  only:
    - master
  tags:
    - wks-runner01


zap_scan:
  extends: vulnerability_scan
  only:
    - master
  tags:
    - wks-runner01


sonar_scan:
  extends: code_scan
  only:
    - master
  tags:
    - wks-runner01


version_job:
  extends: get_version
  only:
    - master
    - pre-production
    - production
  tags:
    - wks-runner01

build_running:
  extends: docker-build
  only:
    - master
  tags:
    - wks-runner01
